### ISSUE TITLE
Adding SetCursorPositionAndClick?

### ISSUE THREAD

**Issue by Terroosh** [Queuete/ExileApi#100]
[UnstackDeck Plugin](https://github.com/IlliumIv/UnstackDecks/tree/1d62688805c9ef89bb35b6d6ceead786f136464f)

Hi, the UnstackDeck plugin uses SetCursorPositionAndClick. Could something like this be added to Core/Input?

Reference, line 270 and 282: [UnstackDeck.cs](https://github.com/IlliumIv/UnstackDecks/blob/1d62688805c9ef89bb35b6d6ceead786f136464f/UnstackDecks.cs#L270/UnstackDecks.cs
)

**Comment by Queuete** [comment]
The answer to this is rather no. I wont add unnecessary functions. 
If this is a highly requested plugin, probably someone will make the required changes to the plugin code to make it work with this fork.
