### ISSUE TITLE
Fail to load

### ISSUE THREAD

**Issue by yaomi88** [Queuete/ExileApi#103]
i have the Issue with my 2cnd pc, on my VMware with win7 lite aero

https://ibb.co/jfncPtD

and now on windows 10 Enterprice ( vm ware edition orignal from windows )

Installed Framework 4.8
VM ware tools
Visual Studio 2019

**Comment by Queuete** [comment]
Win 7 is not supported.

Duplicate: https://github.com/Queuete/ExileApi/issues/97
