### ISSUE TITLE
[3.14] Item mods

### ISSUE THREAD

**Issue by 0xE0D59** [Queuete/ExileApi#121]
Item mods are not currently working. For flasks this makes them unrecognizable for purposes of using instant flasks or remove ailment flasks.
![image](https://user-images.githubusercontent.com/45870990/115129588-ab971880-9fe7-11eb-982d-1a9a16a5c949.png)

**Comment by training0112** [comment]
namespace ExileCore.PoEMemory.MemoryObjects
{
    public class ItemMod : RemoteMemoryObject
    {
          private void ParseName()
          {
                var addr = M.Read<long>(Address + 0x18, 0);
                //....
                _Group = Cache.StringCache.Read($"{nameof(ItemMod)}{Address + 0x18}", () => M.ReadStringU(M.Read<long>(Address + 0x18, 0x70)));
                //...
          }
    }
}
It work for me

**Comment by 0xE0D59** [comment]
Can confirm, this fixes mod names. Good job!

**Comment by 0xE0D59** [comment]
https://github.com/Queuete/ExileApi/pull/123
