### ISSUE TITLE
There was a problem with the plugin update

### ISSUE THREAD

**Issue by Sansuiliang** [Queuete/ExileApi#131]
![2021-04-21 150013](https://user-images.githubusercontent.com/59092117/115510447-53476b80-a2b2-11eb-9aef-414c3ea2933e.png)
Follow your instructions for adding a new plug-in,
This problem keeps appearing,

**Comment by Queuete** [comment]
You seem to be not able to reach the github repositories.

Are you playing on the standalone Poe client? (not Steam / Epic / Tencent ...)

**Comment by Sansuiliang** [comment]
Yes. sure not.
Downloaded from GGG.

**Comment by Queuete** [comment]
The hud fails to send a request to the github server. You are probably using some kind of proxy?
