### ISSUE TITLE
NPC map icons not loading

### ISSUE THREAD

**Issue by deMathias** [Queuete/ExileApi#133]
Hello,

With the latest update the NPC's aren't showing up on the map anymore.

![image](https://user-images.githubusercontent.com/47175867/115515597-97704700-a285-11eb-80bc-e06a54653652.png)

**Comment by wlastas** [comment]
it's not just for NPC's
coz EntityListWrapper EntityList return always 0

**Comment by deMathias** [comment]
fixed with latest update.
