### ISSUE TITLE
Updater not working for like the 5 last updates

### ISSUE THREAD

**Issue by deMathias** [Queuete/ExileApi#135]
always same error:
Log -> updateFolderPath: E:\poe\update
Log -> releaseFileName: PoeHelper
Log -> mainExecuteablePath: E:\poe\Loader.exe
Log -> Cleaning directory: E:\poe\temp
Log -> Try to kill VBCSCompiler.exe
Log -> Try to kill csc.exe
Log -> VBCSCompiler.exe is still running... 50 / 15000
Log -> csc.exe is still running... 80 / 15000
Error -> Something during the update went wrong.
Error -> When you are not able to start the program manually you may need to reinstall it.
Error -> Could not find a part of the path 'E:\poe\update\PoeHelper'.
 
and then i just come to github and download latest version manually.

**Comment by MaelKoT** [comment]
Same for me... Still have 3.13.17 version and cant update.

Solution: 
Completely delete your PoeHelper, and manually download the latest release.
(unfortunately, you will have to re-set all the settings for yourself)

**Comment by Queuete** [comment]
There is probably an error related to this in your hud log. Those are prefixed with "AutoUpdate ->" (so you can search for this string in the error log).
When the folder ...update\PoeHelper does not exist then either the download of the PoeHelper.zip or the unpacking failed. The reason for this is potentially explained in the error messages I mentioned.

**Comment by MaelKoT** [comment]
> edit: @MaelKoT you can also just download the release, unpack it and copy it over your existing files. Replace everything. The settings / plugins are not included in the release so they wont be replaced.
> There are just rare occasions when your settings got corrupted and this process wont work, then you need a fresh install.

Nope, this didnt work. When i just copying and replace folders - i still have "3.13.17" release with Update avaible + Update button.
And when i deleted old release and running new - all works good.

**Comment by Queuete** [comment]
>Nope, this didnt work for me. When i just copying and replace folders - i still have "3.13.17" release with Update avaible >Update button.
Then you have not replaced the files. The version is written in a simple .json file which is included in the release. This is a normal windows copy and replace action, there is nothing I can do for you if you are not able to execute that.

>And i hope everyone understands that "downloading of the PoeHelper.zip or the unpacking failed" is not a real reason
Thats exactly the same thing I said. The reason WHY the download failed (or WHY the unpacking failed) is inside of the hud error logs.

**Comment by deMathias** [comment]
2021-04-21 14:32:23.099 +02:00 [INF] AutoUpdate -> Update .zip file already exists.
2021-04-21 14:32:23.099 +02:00 [ERR] AutoUpdate -> Unzip failed, you may need to delete the content of the folder update manually
2021-04-21 09:30:04.088 +02:00 [ERR] AutoUpdate -> Unzip failed, you may need to delete the content of the folder update manually
[Info-20210421.log](https://github.com/Queuete/ExileApi/files/6352016/Info-20210421.log)
[Verbose-20210421.log](https://github.com/Queuete/ExileApi/files/6352017/Verbose-20210421.log)
[Error-20210421.log](https://github.com/Queuete/ExileApi/files/6352018/Error-20210421.log)

**Comment by Queuete** [comment]
When the unzip failed the .zip file was not deleted (this will happen in the future, just pushed an update).
This means as soon as you ended up with a corrupted .zip file once (e.g. because the hud was killed before the download was completly done) the update process would always fail. 

Thanks for adding the logs, the Verbose one is enough (it contains all the data which is included in the other ones and more). 

You will need to download 3.14.10 manually, if this problem happens afterwards again please open a new issue with the log file!
