### ISSUE TITLE
Last update broke program

### ISSUE THREAD

**Issue by deMathias** [Queuete/ExileApi#148]
![image](https://user-images.githubusercontent.com/47175867/116063733-9aa07400-a685-11eb-9e40-4d2805be0a29.png)
same with clean install

**Comment by snowhawk04** [comment]
Try manually updating. https://github.com/Queuete/ExileApi/releases/

**Comment by deMathias** [comment]
> Try manually updating. https://github.com/Queuete/ExileApi/releases/

Weird, like I said clean install (download release and unzip myself) failed. But in a new fresh folder it does work. Thanks.
