### ISSUE TITLE
Add static Loader.exe

### ISSUE THREAD

**Issue by mm3141** [Queuete/ExileApi#149]
You may consider adding a good Loader.exe as static file in order to workaround the AV false positives, as it is done here https://github.com/IlliumIv/ExileApi/commit/5bb8ddb743c64135b9a00ed8d0ad5df5d9913edb

**Comment by Queuete** [comment]
Just curious, why should this change something about the antivirus detecting it? The resulting archive which is downloaded would look exactly the same, right? (The Loader.exe is already included in the archive)

**Comment by mm3141** [comment]
On my machine, AV kills the Loader.exe only for some of the builds (about half of them), there seems to be some difference which is interesting for the AV

**Comment by Queuete** [comment]
I ran the latest 3 releases through virustotal and they all come back with at least 11 positives. I dont think this would really solve the problem. The only solution is probably excluding the directory from your AV screening.

**Comment by mm3141** [comment]
Try for example this one: https://github.com/Queuete/ExileApi/releases/tag/3.12.0

![image](https://user-images.githubusercontent.com/7443263/116196558-f6293b00-a733-11eb-8ad1-e7d96a52be05.png)

**Comment by Queuete** [comment]
Will look into this this evening, thanks for the link.

**Comment by Queuete** [comment]
It seems like the AV engines have changed in the last 6 month. 
Downloaded the old Loader and uploaded it, with the cached result 6 month ago I saw 0 flags aswell, after rerunning I get the same results as with newer versions:
https://www.virustotal.com/gui/file/2ce9d03732496385722c1d6261e03e45cb581c58fd39c1aa0cf2e0bb190be439/detection

**Comment by mm3141** [comment]
:D caching AV scan results for 6 month makes perfect sense while changing AV signatures multiple times a day

**Comment by mm3141** [comment]
Neither time not motivation to invest into investigating why it sometimes works for Microsoft AV, closing this (although it may be beneficial for AV which remembers exclusions by file hash).
