### ISSUE TITLE
No more drawing

### ISSUE THREAD

**Issue by deMathias** [Queuete/ExileApi#178]
with the latest update the program doesn't draw any of the plugin overlays, it's just a big black box slowly covering the entine screen. Settings HUD en mouseover infopanels do work for some reason.

![image](https://user-images.githubusercontent.com/47175867/119105918-17710480-ba1e-11eb-9632-19d1a2c4e0b3.png)

**Comment by Queuete** [comment]
There was a game update in between which changed some strucutres. Part of it got fixed recently but there is still work to do.
https://github.com/Queuete/ExileApi/pull/179
