### ISSUE TITLE
Does not find plugins

### ISSUE THREAD

**Issue by zlidenskardanom** [Queuete/ExileApi#180]
I'm using the app for the first time, maybe I'm doing something wrong, please send me the installation instructions, I haven't found it anywhere.
I added plugins, but it doesn't display them
Steam client
[logs.zip](https://github.com/Queuete/ExileApi/files/6522915/logs.zip)
![image](https://user-images.githubusercontent.com/60474799/119147520-5a4dcf00-ba54-11eb-8b7a-f500e144ba03.png)
![image](https://user-images.githubusercontent.com/60474799/119147023-e14e7780-ba53-11eb-9602-5a09ad17127c.png)
![image](https://user-images.githubusercontent.com/60474799/119147084-ef9c9380-ba53-11eb-810e-80c94d029742.png)

**Comment by Queuete** [comment]
Steam is not supported.

```
1. The Hud wont start.
...
- make sure you use the standalone client (NOT Steam, NOT Epic Launcher, NOT Taiwan, NOT Tencent)
```
https://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/940986-exileapi-3-14-release.html
