### ISSUE TITLE
issues with extra plugins

### ISSUE THREAD

**Issue by deMathias** [Queuete/ExileApi#184]
![image](https://user-images.githubusercontent.com/47175867/119257400-72912b80-bbc5-11eb-8e3d-c1302533f068.png)

I sometimes have to restart the hud 5-6 times before a newly added plugin will succesfully show up. Sometimes closing the hud doesn't save the settings you have changed in the pluginautoupdate window.

**Comment by Queuete** [comment]
The settings only save when you close the hud. 
From the forum thread:
`
1. F12 (open main menu), Go to "PluginAutoUpdate"
2. Change the settings as you desire e.g. Add a new plugin or change the source url of an existing plugin
3. F12 (save settings), Restart Loader.exe
`

Your posted error message is related to an error in your config/global/PreloadAlert_settings.json file. You either have to correct the faulty line or simply delete the file. When you delete the file a new default file will be created on the next start up.
