### ISSUE TITLE
Traversing element children actually a no-op

### ISSUE THREAD

**Issue by snowhawk04** [Queuete/ExileApi#189]
https://github.com/Queuete/ExileApi/blob/0118228f2364a8a9a9ae9e06e02ad33fefeace52/Core/PoEMemory/Element.cs#L222-L235

Am I missing something here? Should `res` be a referenced argument?

**Comment by Queuete** [comment]
no-op as in Nulloperation? I dont see anything faulty here.

Lists are always passed by reference. Are you talking about the "ref" keyword? This would be only relevant if we want to change the reference (not the list) inside of the method. Adding objects to a list in a method is working although probably not really good style.

Minor example on the ref keyword:
https://dotnetfiddle.net/SXQQc1

**Comment by snowhawk04** [comment]
nevermind. Was an issue on my end with a breakpoint.
