### ISSUE TITLE
Fail to load

### ISSUE THREAD

**Issue by enziyong0823** [Queuete/ExileApi#191]
![제목 없음](https://user-images.githubusercontent.com/85075533/120114598-d796e380-c1ba-11eb-930f-34eedb761e17.png)
windows 10
help

**Comment by Queuete** [comment]
https://github.com/Queuete/ExileApi#troubleshooting

**Comment by enziyong0823** [comment]
> https://github.com/Queuete/ExileApi#troubleshooting

thanks
