### ISSUE TITLE
BasicFlaskRoutine Add "Foreboding" support 

### ISSUE THREAD

**Issue by elvese** [Queuete/ExileApi#20]
Is there any chance to add feature for mana flask to not spam clicking untill flask effect expire? this actually prevents foreboding mana flask from working at all

**Comment by elvese** [comment]
closed accidentaly

**Comment by Queuete** [comment]
I'll keep this here for now. It would fit better into Sychotix BasicFlaskRoutine repository but thats not developed anymore as far as I am aware. Thats definitly no high priority, so dont expect a fix from myself soon.

**Comment by elvese** [comment]
Its ok, thanks for looking onto it. its just something that would be nice to implement in a future, have a good one
