### ISSUE TITLE
offsets fix

### ISSUE THREAD

**Issue by TiuDerca** [Queuete/ExileApi#220]
ModsComponentOffsets
[FieldOffset(0x480)] public int ItemLevel;
[FieldOffset(0x48C)] public int RequiredLevel;

IngameUElementsOffsets
[FieldOffset(0x7C8)] public long DelveWindow;
[FieldOffset(0x7F0)] public long ZanaMissionChoice;

**IngameUElementsOffsets have many broken offsets**

You can fix `SubterraneanChart.GridElement` pls?

**Comment by snowhawk04** [comment]
Can you verify #226 addressed the panels you wanted

**Comment by Queuete** [comment]
Due to no further comment I expect this to be fixed.
