### ISSUE TITLE
Problem with Skills

### ISSUE THREAD

**Issue by totalschaden** [Queuete/ExileApi#225]
ActorSkill.IsOnCooldown is always false.
ActorSkill.RemainingUses is always 0.

**Comment by mm3141** [comment]
I can take a look in 1..2 weeks when I‘m back from vacation

**Comment by wlastas** [comment]
same problem with  ActorSkill.EffectsPerLevel
RequiredLevel  = now is (Address + 0x74+8)? - same value 2 more time
ManaMultiplier now is Address + 0x80 (same +8)
ManaCost  =>Address + 0xa8 absolutely not correct, I tried to find it myself, but could not - it looks like this value is now not one jump from the base address

**Comment by snowhawk04** [comment]
GetSkillUiStatePtr changed in InGameState.ServerData, it'll be in the next pull request. IsOnCooldown and RemainingUses appear to work.

EffectsPerLevel only looks at the **base skill gem** and doesn't account for global stats that reduce/increase mana costs from tree and from linked supports.

0xA8 points to a list of secondary stats (e.g. is_area_damage for flame dash). The base resource cost type is in a list at 0x109. It's corresponding value has the same index in the cost values list at 0x0F9. Again, these are values for the **base skill gem**, not what you see in the tooltip.

**Comment by wlastas** [comment]
> 0xA8 points to a list of secondary stats (e.g. is_area_damage for flame dash). The base resource cost type is in a list at 0x109. It's corresponding value has the same index in the cost values list at 0x0F9. Again, these are values for the **base skill gem**, not what you see in the tooltip.

I understand about the basic skill - I used only the lvl 1 skill without any additional support gems
I tried to find exactly the base 11 (15) mana

**Comment by wlastas** [comment]
By the way, to search for the stats of the skill I'm interested in, I put it in the slot of the right mouse on the panel and get the address on TotalUses. If we subtract 0x54 from it, we get the base address of the ActorSkill structure
```
<CheatEntry>
      <ID>2</ID>
      <Description>"[skill panel=&gt;R mouse slot] actor_skill.TotalUses"</Description>
      <LastState Value="0" RealAddress="252B68FFCA4"/>
      <ShowAsSigned>0</ShowAsSigned>
      <VariableType>4 Bytes</VariableType>
      <Address>"PathOfExile.exe"+02637398</Address>
      <Offsets>
        <Offset>44</Offset>
        <Offset>230</Offset>
        <Offset>1B8</Offset>
      </Offsets>
    </CheatEntry>
```

**Comment by Queuete** [comment]
Those should be solved by now, one of the pull request from @snowhawk04 included changes to this, thanks!
