### ISSUE TITLE
3.15 Broken Things

### ISSUE THREAD

**Issue by snowhawk04** [Queuete/ExileApi#231]
Here's a list of broken stuff I've come by so far if others want to tackle them.

- [x] Advanced Tooltips and Map Mod Notifications require tooltip information currently not working.
- [ ] Locate `MapTabWindowStartPtr` in InGameUElementsOffsets.
- [ ] Locate Diagnostic Elements in InGameState.
- [ ] Locate Terrain SmallMinimap data.
- [ ] Align Terrain LargeMinimap data.
- [ ] Locate `IsCorrupted`, `isSplit`, and `IsUsable` in Mod component.
- [ ] Locate `TrialPassStates` in Player component.
- [x] Locate CanPickUp and TimeLeft in LabelOnGround (requires party).

**Comment by TiuDerca** [comment]
![image](https://user-images.githubusercontent.com/88079618/128197391-2871e10b-78c8-4564-ba44-51a706203bf7.png)
this not work? 

After the last update I get a bunch of errors from plugins where use: "ingameState.IngameUi.Atlas.IsVisible" or "ingameState.IngameUi.AtlasPanel.IsVisible"

**Comment by TiuDerca** [comment]
MinimapIcons (https://github.com/Queuete/MinimapIcons)

2021-08-04 20: 57: 31.886 +07: 00 [ERR] MinimapIcons, Render -> System.MissingMethodException: Method not found: "ExileCore.PoEMemory.Element ExileCore.PoEMemory.MemoryObjects.IngameUIElements.get_AtlasPanel ()".
    at MinimapIcons.MinimapIcons.Render ()
    at ExileCore.Shared.PluginWrapper.Render () at /buddy/exileapi/Core/Shared/PluginWrapper.cs: line 208
    
Map Mod Notifications (https://github.com/IlliumIv/MapNotify)

    2021-08-04 21:58:27.924 +07:00 [ERR] Map Mod Notifications, Render -> System.MissingMethodException: Метод не найден: "ExileCore.PoEMemory.Element ExileCore.PoEMemory.MemoryObjects.IngameUIElements.get_AtlasPanel()".
   в MapNotify.MapNotify.Render()
   в ExileCore.Shared.PluginWrapper.Render() в /buddy/exileapi/Core/Shared/PluginWrapper.cs:строка 208
   
   
![image](https://user-images.githubusercontent.com/88079618/128204624-8e3f5066-0114-4ca8-90c5-b09a19cba9f2.png)
breakpoint not work, but delete fix error.

**Comment by snowhawk04** [comment]
`ExileCore.PoEMemory.Element` tells me you haven't recompiled your plugins.

**Comment by Queuete** [comment]
`If you are having ExileAPI compile your addons, you may need to go into the folders for those two addons and delete the dll's to force them to be recompiled.`

When you update the api to 3.15.21 (e.g. with the update button) and have the auto updater activated for the MinimapIcons plugin it works without any problems.

**Comment by TiuDerca** [comment]
> If you are having ExileAPI compile your addons, you may need to go into the folders for those two addons and delete the dll's to force them to be recompiled.

Thx, fix it

**Comment by ThisIsFineCopium** [comment]
Minimap icons don't show in heist

**Comment by Queuete** [comment]
I will close this, due to being 2 leagues ahead already. If someone wants it reopened, feel free to ping me.
