### ISSUE TITLE
consistently crashing

### ISSUE THREAD

**Issue by Ginfer** [Queuete/ExileApi#242]
Hello, been trying out hud(amazing thing), but for some reason, it's crashing at least once in an hour(covering the whole screen and denying me access to poe client until I manually close the error window).

win 10, vulkan,  using few ahk scripts("Awakened PoE Trade", "LutBot")
[Verbose-20210903.log](https://github.com/Queuete/ExileApi/files/7104048/Verbose-20210903.log)

**Comment by Queuete** [comment]
You activated the debug mode in BasicFlaskRoutine. This is intended to find out whats wrong when one of your flask is triggered. When its active this means there will be roughly 10 entries per second. 
The DebugWindow seems to be not able to handle that many messages. This should not happen, its intended to basically throw away "old" messages when its flooded with new ones but there are some errors in your log which indicate that this is not working correctly currently.

So your best bet is probably to uncheck the "Debug Mode" checkbox in the BasicFlaskRoutine (And the "Debug" checkbox in BuildYourOwnRoutine, in case thats active aswell).

Please give me a short answer if this is solving your problem.

**Comment by Ginfer** [comment]
Played for about an hour w/o any issue(can't test more today), thank you. 

Had a different issue before(flasks sometimes would stop working). The idea was that I could look at debug window to make sure flasks are working. That problem fixed itself(idk how) but seems like constantly opened debug window wasn't the best idea.
