### ISSUE TITLE
some plugins broken

### ISSUE THREAD

**Issue by jeroenymo** [Queuete/ExileApi#246]
MinimapIcons and MiscInformation dont seem to work, while Healthbar does
[Verbose-20211021.log](https://github.com/Queuete/ExileApi/files/7392599/Verbose-20211021.log)

EDIT: it seems that in the last few reboots of the tool, i no longer get errors, though the plugins still dont work.

**Comment by Queuete** [comment]
This was most likely an offset issue, which is normal after new patches.
