### ISSUE TITLE
Issue with Stashie and Pickit Plugins

### ISSUE THREAD

**Issue by rishirocks5** [Queuete/ExileApi#265]
There is an issue with stashie plugin (same stashie plugin in working fine with the https://github.com/IlliumIv  version). After the Hotkey is pressed, only one of the item gets stashed and none of the others are stashed. Please look into this.

Pickit plugin is not working at all.

Thanks.

**Comment by Queuete** [comment]
PickIt and Stashie have their "Simple" counterparts for exactly this reason. There wont be any specific support for those plugins here.
