### ISSUE TITLE
Random Error appears since today

### ISSUE THREAD

**Issue by xhaize** [Queuete/ExileApi#274]
https://imgur.com/a/X2mWVx8

**Comment by JamesCrumble** [comment]
Try to delete config file
**ExileCore.dll.config**

**Comment by xhaize** [comment]
Didnt work sadly

**Comment by therealshibe** [comment]
had same issue. Delete folder and re-download from releases and it works again.

**Comment by xhaize** [comment]
Found a solution, a harsh one, i did a clean windows reinstall and now it works, ty guys for ur help though
