### ISSUE TITLE
make duplicate plugins in `updateSettings.json` (closer to) impossible 

### ISSUE THREAD

**Issue by slippycheeze** [Queuete/ExileApi#29]
G'day.  For not amazing reasons I ended up with a plugin registered twice in my `updateSettings.json` file.  Because that is an array of objects with the key `name`, that duplicate was possible despite both of them having the same name.  

It'd be good to warn if that happened, because it definitely isn't a valid situation, and caused problems.

It'd be better to make the `Plugins` field an object, keyed by name, so that it was pretty much impossible for someone with a text editor and an intention to mess things up. :)   

IDK if that was already the plan, but either way, figured it was worth mentioning.  Error was a compile failure, and it took a lot of poking about to figure out what the cause was.

Failure was — and I foolishly deleted the logs, but — `.../{plugin}.dll is in use by another process` for the second one.  Plus an update failure for the repo.

**Comment by Queuete** [comment]
Hello,

Changing from array to object wont do anything about the .json file, except [] braces switching to {} braces. Changing the structure of the object would maybe make those issues easier to see, but thats nothing I want to optimize for. The UI is the intended way to interact with the file, if you know what you are doing there is no problem with editing the file directly (as you have done successful aswell ;).
When editing the file directly there is no way to make duplicates impossible.

When adding or changing a plugin through the UI you will now see an red error message when there are duplicated plugins.

Best Regards
Queuete
