### ISSUE TITLE
The all UIs of plugins are offset

### ISSUE THREAD

**Issue by daxigua249121589** [Queuete/ExileApi#296]
Hello,

When I install it, all UIs are offset. How to fix it? TYVM

:)

Howard

![QQ20220126233124](https://user-images.githubusercontent.com/6355595/151205752-b135061f-454c-4950-b4bd-13b69e6610c9.png)
![QQ20220126233139](https://user-images.githubusercontent.com/6355595/151205792-223de4d8-0482-4067-91e7-855613841e52.png)

**Comment by daxigua249121589** [comment]
I use the defaul plugins and settings. No changes on the settings

**Comment by Queuete** [comment]
This is most likely an issue which can be solved by point 3 of the Troubleshooting section int he Readme. https://github.com/Queuete/ExileApi#troubleshooting
