### ISSUE TITLE
Someone update tencent version? I will sponsor

### ISSUE THREAD

**Issue by wuhaibo867** [Queuete/ExileApi#315]
Someone update tencent version? I will sponsor each season or update $200 at a time. I can provide documents and need to prepare. Please contact the DISCORD: poeplayer# 9197. Long-term cooperation can improve sponsor fee can be negotiated

**Comment by face0206** [comment]
face0206@outlook.com

**Comment by Queuete** [comment]
A "official" tencent version is not planned. Due to inactivity in here I will close this for now.
