### ISSUE TITLE
Automatic compilation feature suggestion

### ISSUE THREAD

**Issue by snowhawk04** [Queuete/ExileApi#33]
The default behavior of the downloader should be a user request to update, not forcing an update on load. There are security concerns and being on the bleeding edge of a development cycle may not always be a good thing. Personally, I'd like to see the updater stripped out and made into a plugin.

**Comment by Queuete** [comment]
I agree with you the updates should not be forced on start but optionally done manually with notifications when a certain plugin contains updates. 

I disagree with making this into a plugin. Plugins should not access each other.

**Comment by Queuete** [comment]
https://github.com/Queuete/ExileApi/pull/145

This is done now. When you deactivate the auto update feature for a specific plugin you can enter a "Commit Sha" (the long version, 40 characters). The plugin will download and compile this commit and present you an update button in case there is a newer commit. When you press it, the chosen commit gets updated and during the next restart the newest commit will be used. 

The Menu shows how many plugins have an update available.

The auto update mechanismn is an "opt out" feature, so by default its still enabled and nothing should have changed.
