### ISSUE TITLE
ItemEntity should have "IsQuestItem" value

### ISSUE THREAD

**Issue by 13413j1j13j5315n13** [Queuete/ExileApi#34]
To reproduce:
1. A quest item should be on the ground. Example could be "Haliotis Glyph"
2. Open DevTree
3. Entities -> proper WorldItem -> Components -> WorldItem -> ItemEntity

The entity will have many fields such as "IsOpened", "IsHostile", "Rarity" etc. 
As the item type is quest related item ExileApi should have "IsQuestionItem" field as True.

**Comment by Queuete** [comment]
Done by @snowhawk04 in PR #32
