### ISSUE TITLE
Accessing GameController.Entities sometimes throws "Collection was modified; enumeration operation may not execute"

### ISSUE THREAD

**Issue by 13413j1j13j5315n13** [Queuete/ExileApi#35]
Iterating over `GameController.Entities` sometimes gives `Collection was modified; enumeration operation may not execute` error.

Example codes:
```
IEnumerable<Entity> players = GameController.Entities.Where(e => e.Type == EntityType.Player);
Entity leaderPlayer = players.FirstOrDefault(e => e.GetComponent<Player>().PlayerName == Settings.FollowerModeSettings.LeaderName.Value);
```
or
```
return GameController.Entities
    .Where(x => x.Type == EntityType.Player)
    .FirstOrDefault(x => x.GetComponent<Player>().PlayerName == leaderName);
```

Tried `.ToList()` as well but still gives the error. For now I just wrapped in try/catch.

**Comment by Queuete** [comment]
Yes, thats not really changeable in the current state. There are 2 options, the first and "easiest" is your try/catch approach. The other option would be to overwrite the "EntityAdded(Entity entity)" method and either do your logic in there or building your own Entity collection (e.g. as a ConcurrentBag).

I will look into changing the GameController.Entities to a threadsafe Datatype, but thats most likely a breaking change for lots of plugins. When thats the case I wont do that.

**Comment by snowhawk04** [comment]
Have you considered `ValidEntitiesByType[]`?

 `var players = GameController.EntityListWrapper.ValidEntitiesByType[EntityType.Player];`

**Comment by 13413j1j13j5315n13** [comment]
I think we should close this issue as there are work arounds and this is definitely a low priority bug. Better to spend time doing something else.
