### ISSUE TITLE
Build failed for latest release

### ISSUE THREAD

**Issue by Barragek0** [Queuete/ExileApi#360]

**Comment by hborg004** [comment]
Null reference exception for local player path:

System.NullReferenceException: 'Object reference not set to an instance of an object.'

ExileCore.PoEMemory.MemoryObjects.Entity.Path.get returned null.

**Comment by therealshibe** [comment]
Auto-update wasn't working and .zip didn't make it into the release posted. I was able to build it myself though.

**Comment by Queuete** [comment]
> Auto-update wasn't working and .zip didn't make it into the release posted. I was able to build it myself though.

Pushing the .zip rarely fails, when github is slow on creating the release. When there is no zip, the AutoUpdater fails. If this happens more often I will increase the delays in there, but for now I just manually reran the pipeline. The latest release now contains the zip file.
