### ISSUE TITLE
Inter-plugin communication in PoeHud

### ISSUE THREAD

**Issue by 13413j1j13j5315n13** [Queuete/ExileApi#41]
I sometimes see that in plugins people keep reinventing wheels and implement the same logic all over again.

Would it make sense to consider inter-plugin communication in PoeHud?
I don't have a clear vision how this should be implemented but I guess we might benefit from inter-plugin communication because:
1. The whole community can create helper plugin which will gather the best ideas and helper functions. Like a library. This can be used by all plugins.
1. Reduce code size in plugins due to the fact that many functions will be already implemented in the helper plugin.
1. I guess helper functions will have less bugs.

Any other benefits? Any thoughts?

**Comment by Queuete** [comment]
I dont think a plugin is the right choice for that. 
Plugins are meant to be rendered or run frequently. Your suggestion rather seems to be a library. Those Helper functions most likely rather fit directly into the exposed ExileApi.
Do you got any concrete examples which type of functionality should be centralized?

**Comment by slippycheeze** [comment]
core function: "is a game UI of any sort shown?"
 - don't auto-cast while syndicate UI, or mitemarph UI, or <next league> UI is shown.

Shows up in a bunch of places where the code checks for some set of UI elements being visible.

**Comment by Queuete** [comment]
@slippycheeze This might be a candidate for core functionality in the ExileApi then. But I dont really see the point. The requirements differ for different Plugins. Some of those windows are opened mid fight (e.g. syndicate single member UI, metamorph...) should the FlaskRoutine or some AutoCast plugin really stop when those are not visible? And should they also stop when the inventory is opened? So which are the "relevant UIs"?

This still seems to me like something which should be solved on Plugin level.

**Comment by Queuete** [comment]
I'll close this. If you encounter such features which fit into the Core feel free to open a new ticket or revive this one.
