### ISSUE TITLE
CoPilot & ChatBox offset

### ISSUE THREAD

**Issue by snowhawk04** [Queuete/ExileApi#46]
From the [forums](https://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/887225-copilot-plugin-poehelper-poehud-exileapi-post4258009.html#post4258009)

> > Originally Posted by Soiseiseki View Post
> > chat window offset is broken, to quick fix:
> >     
> > in file CoPilot.cs ->> line 437
> > replace `if (buffs.Exists(x => x.Name == "grace_period") || GameController.IngameState.IngameUi.ChatBox.Parent.Parent.Parent.GetChildAtIndex (3).IsVisible)`
> > to `if (buffs.Exists(x => x.Name == "grace_period"))`

> Works fine on the Fork I use, if this is not working for you the ChatBox offset is most likely broken on your fork. You can ask the Person who is maintaining the fork to have a look at it. Or change code as Soiseiseki suggested.
> Keep in mind changing the code results in Copilot possibly spamming into your chat window when you write someone.

I asked for more info on where `ChatBox` starts and what GetChildAtIndex(3) is.

> Yes, `ChatBox.GetChildAtIndex(0)` is the first msg of chat history.
> Yes, `ChatBox.Parent.Parent.Parent.GetChildAtIndex(3)` is the "Input field" where you enter the text you want to send.

To give an idea of what the ChatBox structure looks like

```
Root > [x]ChatBox Panel > [0]Toggle Panel  > [0]Channel Bar Panel
                                           > [1]Hide ChatBox Button Panel
                        > [1]History Panel > [0]Feature Placeholder
                                           > [1]Feature Placeholder
                                           > [2]Chat Body Panel      > [0]Feature Placeholder
                                                                     > [1]Chat History Panel
                                                                     > [2]Chat Scroll Panel
                        > [2]Target Channel Panel
                        > [3]Text Input Panel
                        > [4]Autocomplete Panel
```

So in the fork they develop with, the `ChatBox` offset points to `[1]Chat History Panel`. They traverse up the tree with `Parent.Parent.Parent` to get to the `ChatBox` element our offset currently points to (`[x]ChatBox Panel`). I'm not sure how you want to handle such conflict moving forward. Should we insist we have the right offset and they should modify their addon? Should we accommodate the author and change the offset to the grandchild element (document it, introduce a new property for the chatbox root element)?

**Comment by Queuete** [comment]
> Should we accommodate the author and change the offset to the grandchild element (document it, introduce a new property for the chatbox root element)?

Thats probably the way I would want to take.

**Comment by snowhawk04** [comment]
#47 fixes this.
