### ISSUE TITLE
Default plugins

### ISSUE THREAD

**Issue by Queuete** [Queuete/ExileApi#53]
Hello guys,

I am planning to shrink down the default plugins.
The main reasons:
- dont overwhelm new users with plugins
- reduce initial "not working" plugins on league start (establish the default plugins as core which should work as fast as possible)
- have a normal hud experience on startup (compareable to TurboHud for Diablo), without too much "almost bot" or "clearly cheating" features
- users who want more plugins are forced to do at least a little bit of research (I still plan to have a "full" list of plugins in the thread)

furthermore I want to get away from using my forked plugins. I did this when I started this ExileApi fork, because back then the compile path did matter. As this is not the case anymore (due to the AutoPluginUpdater) I would like to include the currently maintained (or most recent) version of the plugins.

HealthBars: (stick to my fork, due to low amount of changes?)
MinimapIcons: (stick to my fork, due to low amount of changes?)
IconsBuilder: (stick to my fork, due to low amount of changes?)
Stashie: Craere / nymann (when the reference issues are solved)
BasicFlaskRoutine: ?
PreloadAlert: ?
PickIt: DetectiveSquirrel?
(BuffUtil) is there any kind of up to date version?

I appreciate input from everyone and especially (@snowhawk04 @mm3141 @Craere) on which repositories should be taken and the whole topic.

Best Regards 
Queuete

**Comment by snowhawk04** [comment]
MiscInformation and Iconsbuilder are probably the only ones that should be included, just to show the basic stuff works. The original [Pluginsupdater by Zaafar](https://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/625598-poehud-plugin-poehud-pluginsupdater.html) provided a list of available plugins users could select to install. Developers could opt-in to having their plugin delivered this way, which means they are likely developing for this branch. Users don't have to go digging for git urls and work around duplicate entries. Core maintainers don't have to provide support as every addon had a link to a thread on the OC forums.

Just to provide some data though, this is what I'm currently using in Heist HCSSF: _DevTree, Stashie, Pickit, UnIdy, Iconsbuilder + MinimapIcons + HeistIcons, BasicTreeRoutine (BasicFlaskRoutine), Terrain, HighlightedItems,_ and a stripped down version of _RandomFeatures_.  

The recent iterations of _AutoOpen_ are too sketchy to use on HC.
_MapExchange, PreloadAlert_ and _ItemAlert_ seem like artifacts from PoE pre-3.0. 
_Proximity Alert, HealthBars, RandomFeatures,_ and _AdvancedUberLabLayout_ all seem like they would be popular addons. _BuffUtil, CoPilot, MineDetonator, ScourgeArrowCharges,_ etc skill addons all seem pretty niche. _CoPilot_ is probably the best of the bunch, but _BasicTreeRoutine_ allows me to switch my profile in game. 
_XPBar_ is pointless as _MiscInformation_ gives information that is probably more useful to the player. 
_TowerDefense, Craftie, Tradie, Follower, Passive Skill Tree Planter, Ninja Pricer_ and many more I've just never touched.

**Comment by Queuete** [comment]
Thanks, thats definitely useful feedback. MiscInformation is a good addition and I will most likely remove BuffUtil from the list.

In terms of functionality the PluginUpdater from Zaafar seems good (thanks for the link) thats what I aim for long term.
