### ISSUE TITLE
Changing hideouts 2 or more times in a row causes PoeHud to stuck

### ISSUE THREAD

**Issue by 13413j1j13j5315n13** [Queuete/ExileApi#60]
The initial configuration:
1. 2 machines, PoeHud + Follower + standard plugins used.
1. Follower plugin works correctly.
1. Both characters start in Oriath.

Working flow:
1. Follower changes hideout to leader's.
1. Follower is able to press keys (follows the leader, reacts to commands, enters portals etc.).

Broken flow 1:
1. Follower changes hideout to leader's, everything works.
1. Follower changes hideout to his.
1. PoeHud does not move mouse anymore neither is able to press keys (e.g. doesn't follow).

Broken flow 2:
1. Follower changes hideout to his.
1. Follower changes hideout to leader's.
1. PoeHud does not move mouse anymore neither is able to press keys (e.g. doesn't follow).

Any amount of hideout changes (e.g. back to leader's, back to follower's) does not have any effect, it remains broken.

Visiting any area or town solves the issue and follower continue to follow. Issue comes back after replicating any of the broken flows.

Nothing in logs on both sides. No errors or crashes from PoeHud.

**Comment by Queuete** [comment]
> PoeHud does not move mouse anymore neither is able to press keys (e.g. doesn't follow).

How did you confirm that PoeHud was stuck and not the FollowPlugin? 
I guess your Follower runs in a virtual machine? Does this also happen the other way around, when your follower runs native and your leader in the virtual machine?

**Comment by 13413j1j13j5315n13** [comment]
Can confirm the same with BasicFlaskRoutine.

Pre configuration:
1. Start PoeHud with only BasicFlaskRoutine enabled (no Follower or any other plugins).
1. In BasicFlaskRoutine enable `Enable in hideout` and set health/mana flasks. For mana set `Min Mana % Auto Mana Flask...` as 70
1. Start in Oriath.

Working flow:
1. Enter your own hideout.
1. Set auras up, almost all mana reserved.
1. Remove auras, BasicFlaskRoutine will use a mana flask to recover mana.

Broken flow:
1. Enter your own hideout.
1. Enter other player's hideout.
1. Remove (or set and then remove) auras.
1. BasicFlaskRoutine does not use the mana flask to recover mana.

After visiting any other location or town BasicFlaskRoutine will start recovering mana.

Broken flow is replicable.
Followers are in virtual machine and one running natively on a separate gaming laptop.

**Comment by Queuete** [comment]
I am not able to replicate this behavior. As soon as I remove the aura the mana flask is triggered.

**Comment by Queuete** [comment]
@13413j1j13j5315n13 do you still experience this issue?
