### ISSUE TITLE
Infected!

### ISSUE THREAD

**Issue by VeryTraveller** [Queuete/ExileApi#63]
Releases 105 3.12.39 is infected. pls fix it

**Comment by Queuete** [comment]
https://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/922954-exileapi-3-12-release-24.html#post4264139

This program is exactly in the same state as before. Most likely your windows defender / antivirus got updated.
If you dont trust the releases (which is a totally valid thing, I am just a random guy from the internet ;)) feel free to build it yourself. Its completly open source, nothing except the code in this repository is required.

The ExileApi reads the Memory of another process and downloads and compiles custom code (Plugins) at runtime. Most likely one of those 2 is considered as "virus behaviour" by some of the anti virus providers.

**Comment by VeryTraveller** [comment]
Im using old one and not infected. What is the differances ?

**Comment by Queuete** [comment]
Feel free to look through the commits for differences. As mentioned the virus detection is most likely caused by an antivirus / defender update and not by differences in the ExileApi

**Comment by VeryTraveller** [comment]
**Old version**
![image](https://user-images.githubusercontent.com/73843424/97903296-dd753500-1d4f-11eb-96c6-73ff1b029a2e.png)


**Last Version**
![image](https://user-images.githubusercontent.com/73843424/97903536-3fce3580-1d50-11eb-89a4-85969761f16a.png)

Maybe your pc infected. Pls scan your computer

**Comment by VeryTraveller** [comment]
Why did you close the thread if its safe and trusting yourself ?
