### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by qinshaoding** [Queuete/ExileApi#64]
look like some offset error
   在 TreeRoutine.DefaultBehaviors.Helpers.FlaskHelper`2.GetAllFlaskInfo() 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\DefaultBehaviors\Helpers\FlaskHelper.cs:行号 25
   在 TreeRoutine.Routine.BasicFlaskRoutine.BasicFlaskRoutine.FindFlaskMatchingAnyAction(List`1 flaskActions, Nullable`1 instant, Boolean ignoreBuffs, Func`1 ignoreFlasksWithAction, Boolean isCleansing) 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\BasicFlaskRoutine\BasicFlaskRoutine.cs:行号 318
   在 TreeRoutine.Routine.BasicFlaskRoutine.BasicFlaskRoutine.<>c__DisplayClass41_0.<CreateUseFlaskAction>b__0(Object x) 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\BasicFlaskRoutine\BasicFlaskRoutine.cs:行号 228
   在 TreeRoutine.DefaultBehaviors.Actions.UseHotkeyAction.Run(Object context) 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\DefaultBehaviors\Actions\UseHotkeyAction.cs:行号 35
   在 TreeRoutine.TreeSharp.Action.<Execute>d__12.MoveNext() 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\TreeSharp\Action.cs:行号 75
   在 TreeRoutine.TreeSharp.Composite.Tick(Object context) 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\TreeSharp\Composite.cs:行号 143
   在 TreeRoutine.TreeSharp.PrioritySelector.<Execute>d__2.MoveNext() 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\TreeSharp\PrioritySelector.cs:行号 60
   在 TreeRoutine.TreeSharp.Composite.Tick(Object context) 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\TreeSharp\Composite.cs:行号 143
   在 TreeRoutine.TreeSharp.Decorator.<Execute>d__10.MoveNext() 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\TreeSharp\Decorator.cs:行号 78
   在 TreeRoutine.TreeSharp.Composite.Tick(Object context) 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\TreeSharp\Composite.cs:行号 143
   在 TreeRoutine.TreeSharp.PrioritySelector.<Execute>d__2.MoveNext() 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\TreeSharp\PrioritySelector.cs:行号 60
   在 TreeRoutine.TreeSharp.Composite.Tick(Object context) 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\TreeSharp\Composite.cs:行号 143
   在 TreeRoutine.TreeSharp.Decorator.<Execute>d__10.MoveNext() 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\TreeSharp\Decorator.cs:行号 78
   在 TreeRoutine.TreeSharp.Composite.Tick(Object context) 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\TreeSharp\Composite.cs:行号 143
   在 TreeRoutine.TreeSharp.PrioritySelector.<Execute>d__2.MoveNext() 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\TreeSharp\PrioritySelector.cs:行号 60
   在 TreeRoutine.TreeSharp.Composite.Tick(Object context) 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\TreeSharp\Composite.cs:行号 143
   在 TreeRoutine.TreeSharp.Decorator.<Execute>d__10.MoveNext() 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\TreeSharp\Decorator.cs:行号 78
   在 TreeRoutine.TreeSharp.Composite.Tick(Object context) 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\TreeSharp\Composite.cs:行号 143
   在 TreeRoutine.BaseTreeRoutinePlugin`2.TickTree(Composite treeRoot) 位置 C:\Users\Administrator\Desktop\PoeHelper\Plugins\Source\BasicFlaskRoutine\src\TreeRoutine\BaseTreeRoutinePlugin.cs:行号 113

**Comment by Queuete** [comment]
Yes, some offsets changed in GGGs last patch. Snowhawk and mm3141 fixed already most of them.
