### ISSUE TITLE
Entities list is empty

### ISSUE THREAD

**Issue by marryjane32** [Queuete/ExileApi#67]
So I've noticed recently that the entities list is shown as empty in the DevTree plugin. Is there any specific different in the way memory is read(?) between win7 and win10? Everything seems to work win10, but i dont think there is gonna be difference in the memory reading correct?

**Comment by Queuete** [comment]
Last patch broke some offsets. The EntityList was not broken as far as I am aware. 
I dont know the exact differences between windows 7 and 10. This program works with Windows 10. 
Windows 7 is not supported and wont be in the future.
