### ISSUE TITLE
How can I get terrain altitude(z) info?

### ISSUE THREAD

**Issue by beanbean97** [Queuete/ExileApi#69]
I'm developing a plugin that can auto move to an position(use TerrainData grid info),grid coord map to world coord need z info to calc screen postition. Is there any way to find out that info?(or some clue to find out?),thanks!

**Comment by Queuete** [comment]
This sounds a lot like a bot(like) plugin. I wont support bot developement, sorry. 

ExileApi is kind of tolerated by GGG. A bot based on ExileApi is therefore threatening this "relationship".

**Comment by beanbean97** [comment]
ok,thank you for the answer!
