### ISSUE TITLE
Editing a plugin to work with ExileApi

### ISSUE THREAD

**Issue by zerger3** [Queuete/ExileApi#71]
Hi, i try to edit the "maphelper" plugin to add a feature.
ATM it only highlights reflect maps and unid maps and i want to add Nemesis and other mapmods.

When i check the code i found the dev used

`                     else if (mod.Record.Group == "MapMonsterPhysicalReflection" && Settings.PhysReflect)  //phys reflect
                    {
                        var drawRect = map.GetClientRect();
                        drawRect.X -= 5;
                        drawRect.Y -= 5;
                        badmaps.Add(drawRect);
                        badmods++;
                    }`

Well if i understand it right, exileapi is just a framework. where  can i see a list of available commands to work with the framework?  Where do i find a list of these Mapmod references? 
(im new to this, and i want to start small by editing  a working plugin)

**Comment by zerger3** [comment]
Ok well i figured out how to compile exileapi myself  with devtree :)
i found that the mapmods can be found under 
item -> components->mods there is stuff like reflect etc
what i cant find is monster pack size, intm quantity and rarity and atlas region.

**Comment by Queuete** [comment]
> what i cant find is monster pack size, item quantity and rarity and atlas region.

Those are technically no mods. 
DevTree is the right approach to find data you need. There is no documentation, so to find the available methods you need to check the code.
All plugins need to inherit the "BaseSettingsPlugin<TSettings>", so this should be your starting point when you look for functionality. The game related data is in the "GameController".

**Comment by zerger3** [comment]
well coming from other hack frameworks there was at least a basic command list supplied, eg how to build a menu. how to use click() etc :(

**Comment by Queuete** [comment]
This is not a "hack framework". Its an overlay with an Interface to the PoE Memory. 
The list of "commands" is the BaseSettingsPlugin I told you about:
https://github.com/Queuete/ExileApi/blob/master/Core/BaseSettingsPlugin.cs

There is no "click()" functionality included, because thats not the main intend of this project. If you want to automate the mouse or keyboard input you need to implement this yourself / use another library for it.
