### ISSUE TITLE
followup question

### ISSUE THREAD

**Issue by zerger3** [Queuete/ExileApi#73]
yeah well that is semantics :) i do not wish to automate stuff and i used click() just as an example since i saw it pickit use it.

what is the best place to ask question? i am new to working with VS and wanted to look into some basic stuff for plugins. should i write on ownedcore or on github? maybe the new discussion feature of github could be of interest. thank you for your time :)
sorry for opening a new issue

**Comment by Queuete** [comment]
That most likely depends what kind of question you have. For most stuff OwnedCore is probably the right choice. If you got a specific question regarding the API with concrete code references it might be better suited in here. 

Btw. I am pretty sure you can write in closed issues? Next time please post your follow up in the according issue even when its closed. I should still get an email and will most likely answer at some point.

**Comment by zerger3** [comment]
ok thx wil ldo
