### ISSUE TITLE
WorldItem.ItemEntity wrong offset?

### ISSUE THREAD

**Issue by uragan1987** [Queuete/ExileApi#74]
hi

can you check pls 
got WorldItem pointer, but ItemEntity is always NULL

\Core\PoEMemory\Components\WorldItem.cs
look like,: ReadObject<Entity>(Address + 0x28)  offset isnt right??

**Comment by Queuete** [comment]
The lesser used offsets are most of the time not updated. The next league is starting in ~2 weeks thats the point in time when most offsets will change and be updated afterwards if necessary. 
For what kind of plugin do you need this specific offset?

**Comment by uragan1987** [comment]
just need some more information, how you start to search it, if you need for example WorldItem offset
or how you know, who parent of WorldItem.
are SDKs inside game files?

**Comment by Queuete** [comment]
The tools used mostly are Cheat Engine, ReClass.NET and potentially Ghidra. Get yourself familiar with at least one of the first 2 tools and try to comprehend some already updated offsets. The easiest example is the current/max life, mana and ES of a character.

There is nothing like an SDK. When you already have the base adress you move to this adress in the memory viewer of the tool of your choice. Then you try to make sense of the presented values. Searching pointers is probably a bit more advanced compared to looking for integer values. There are some tutorials on youtube which help with the basics, e.g.
https://www.youtube.com/watch?v=YaFlh2pIKAg
