### ISSUE TITLE
How can I support Tencent service?

### ISSUE THREAD

**Issue by ge1283696102** [Queuete/ExileApi#85]
I really need exileapi, but I'm not a novice and I don't know how to compile. Can I update and support Tencent service?

**Comment by Queuete** [comment]
If you have to ask this question you most likely cant.
I have no clue what the differences for the tencent client are. At least this file would need some changes, but there are probabyl more.
https://github.com/Queuete/ExileApi/blob/master/Core/PoEMemory/Offsets.cs

**Comment by tswierkot** [comment]
> I really need exileapi, but I'm not a novice and I don't know how to compile. Can I update and support Tencent service?

You might want to check on OwnedCore forums, TehCheat used to release a Tencent version of his ExileAPI fork.

**Comment by ge1283696102** [comment]
Hi, I am so stupid. I have been studying for several days and still can't get ExileAPI to support Tencent server. Thank you very much for telling me about TehCheat, he once released Tencent version, but he hasn't updated it for a long time. After several days of research, I found that the latest version you released can be exhaled in Tencent server, and the HUD page has been loaded, but it doesn't work. What is the reason? Thank you for answering my questions. If you can help me update the exileAPI mobile server, I am willing to pay you 50 dollars for each update. Although I know this will make you unhappy, please forgive me. I am an exileAPI
