### ISSUE TITLE
About exileapi in Tencent service?

### ISSUE THREAD

**Issue by ge1283696102** [Queuete/ExileApi#86]
Hi, I am so stupid. I have been studying for several days and still can't get ExileAPI to support Tencent server. Thank you very much for telling me about TehCheat, he once released Tencent version, but he hasn't updated it for a long time. After several days of research, I found that the latest version you released can be exhaled in Tencent server, and the HUD page has been loaded, but it doesn't work. What is the reason? Thank you for answering my questions. If you can help me update the exileAPI mobile server, I am willing to pay you 50 dollars for each update. Although I know this will make you unhappy, please forgive me. I am an exileAPI

**Comment by Queuete** [comment]
I answered those Tencent questions often enough. Its not supported and wont be. I have no clue whats the differences between Tencent and standalone. If someone works it out and wants it included in here feel free to send a pull request. 
I am sorry, but money wont change this.
