### ISSUE TITLE
Roslyn compilator locks the roslyn folder

### ISSUE THREAD

**Issue by Relvl** [Queuete/ExileApi#89]
Roslyn compilator locks the roslyn folder sometimes.
This does not allow you to update the program regularly, you have to download a new release. I suggest killing the compiler process before upgrading if all plugins are already compiled.

**Comment by Jawlen** [comment]
This would explain why I've never been able to get it to auto update.

**Comment by Queuete** [comment]
Thanks for the report, thats a good catch.
Do you know the exact process which blocks it? is it the "csc.exe"? Never happened on my end, therefore its hard to debug. 

Updater and main program are not directly connected, so "killing the proces if all plugins are compiled" is not easily possible. But killing the compiler anyway should be a safe choice. Even if its not done it gets restarted after the update.

**Comment by Queuete** [comment]
The latest update should fix this, please open another issue if it does not, Thanks!

**Comment by Relvl** [comment]
![image](https://user-images.githubusercontent.com/4003026/105839150-ded29880-5ff2-11eb-93a2-279cff6ed663.png)
Not tried yet, but this is the process

**Comment by Queuete** [comment]
Thanks, figured out it might be VBCSCompiler.exe / csc.exe so they are killed both.
