### ISSUE TITLE
Monster on Minimap not working

### ISSUE THREAD

**Issue by fanto88** [Queuete/ExileApi#96]
The plugin to show monster on the minimap doens't seems to works, any solution?

**Comment by tswierkot** [comment]
It is working.
![image](https://user-images.githubusercontent.com/9085368/107154336-c22f4c80-6972-11eb-90c2-e0b8fc1a1be1.png)

Make sure you have the IconsBuilder plugin turned on, MinimapIcons turned on and "Draw Monster" option turned on in MinimapIcons plugin. If you have the "Draw Only on large Map" option turned on, you won't have the monsters drawn on minimap.
![image](https://user-images.githubusercontent.com/9085368/107154395-06bae800-6973-11eb-9107-8d66edf345c3.png)

**Comment by fanto88** [comment]
Yeah, i'm sorry. For some reason yesterday wasn't working, today after a restart of the computer it was working
