### ISSUE TITLE
Crashes without sound device

### ISSUE THREAD

**Issue by tswierkot** [Queuete/ExileApi#97]
PoeHUD doesn't run without a sound device. It shouldn't be dependant on it.
![image](https://user-images.githubusercontent.com/9085368/107270116-d47cb980-6a4a-11eb-8711-62d21c2f1955.png)

**Comment by Queuete** [comment]
Yes, thats known and I agree with you. Nevertheless this probably wont change soon.

**Comment by Queuete** [comment]
https://github.com/Queuete/ExileApi/commit/f9d2e3af36fdb2ccecf28b49532dde56b43f8a09
